<?php

declare(strict_types=1);

namespace Item\Translator;

class TranslatorRU implements TranslatorInterface
{
    private static array $lang = [
        'Potion'                         => 'Зелье',
        'Material'                       => 'Материал',
        'Book'                           => 'Книга',
        'sword'                          => 'Меч',
        'axe'                            => 'Топор',
        'mace'                           => 'Булава',
        'dagger'                         => 'Кинжал',
        'spear'                          => 'Копье',
        'wand'                           => 'Жезл',
        'heavy sword'                    => 'Тяжелый Меч',
        'heavy axe'                      => 'Тяжелый Топор',
        'heavy mace'                     => 'Тяжелая Булава',
        'bow'                            => 'Лук',
        'staff'                          => 'Посох',
        'two hand sword'                 => 'Двуручный Меч',
        'two hand axe'                   => 'Двуручный Топор',
        'two hand mace'                  => 'Двуручная Булава',
        'two hand heavy sword'           => 'Двуручный Тяжелый Меч',
        'two hand heavy axe'             => 'Двуручный Тяжелый Топор',
        'two hand heavy mace'            => 'Двуручная Тяжелая Булава',
        'lance'                          => 'Пика',
        'crossbow'                       => 'Арбалет',
        'ring'                           => 'Кольцо',
        'amulet'                         => 'Амулет',
        'helmet'                         => 'Шлем',
        'armor'                          => 'Нагрудный Доспех',
        'gloves'                         => 'Перчатки',
        'boots'                          => 'Обувь',
        'legs'                           => 'Ноги',
        'shoulders'                      => 'Наплечники',
        'shield'                         => 'Щит',

        // magic types
        'Common item'                    => 'Обычный предмет',
        'Magic item'                     => 'Магический предмет',
        'Enchanted item'                 => 'Зачарованный предмет',
        'Rare item'                      => 'Редкий предмет',
        'Mystical item'                  => 'Мистический предмет',
        'Legendary item'                 => 'Легендарный предмет',
        'Epic item'                      => 'Эпический предмет',
        'Artifact'                       => 'Артефакт',
        'Relic'                          => 'Реликвия',

        // magic affix
        'offense.physicalDamage'         => 'Физический урон',
        'offense.fireDamage'             => 'Урон огнем',
        'offense.waterDamage'            => 'Урон водой',
        'offense.airDamage'              => 'Урон воздухом',
        'offense.earthDamage'            => 'Урон землей',
        'offense.lifeDamage'             => 'Урон магией жизни',
        'offense.deathDamage'            => 'Урон магией смерти',
        'offense.attackSpeed'            => 'Скорость атаки',
        'offense.castSpeed'              => 'Скорость создания заклинаний',
        'offense.criticalChance'         => 'Шанс критического удара',
        'offense.criticalMultiplier'     => 'Сила критического удара',
        'offense.criticalStun'           => 'Оглушает при критическом ударе',
        'offense.criticalBleeding'       => 'Вызывает кровотечение при критическом ударе',
        'base.life'                      => 'Здоровье',
        'base.mana'                      => 'Мана',
        'offense.increasePhysicalDamage' => 'Физический урон',
        'offense.increaseFireDamage'     => 'Урон огнем',
        'offense.increaseWaterDamage'    => 'Урон водой',
        'offense.increaseAirDamage'      => 'Урон воздухом',
        'offense.increaseEarthDamage'    => 'Урон землей',
        'offense.increaseLifeDamage'     => 'Урон магией жизни',
        'offense.increaseDeathDamage'    => 'Урон магией смерти',
        'defense.physicalResist'         => 'Сопротивление физическому урону',
        'defense.fireResist'             => 'Сопротивление урону огнем',
        'defense.waterResist'            => 'Сопротивление урону водой',
        'defense.airResist'              => 'Сопротивление урону воздухом',
        'defense.earthResist'            => 'Сопротивление урону землей',
        'defense.lifeResist'             => 'Сопротивление урону магии жизни',
        'defense.deathResist'            => 'Сопротивление урону магией смерти',
        'base.strength'                  => 'Сила',
        'base.dexterity'                 => 'Ловкость',
        'base.intelligence'              => 'Интеллект',
        'base.will'                      => 'Воля',
        'base.endurance'                 => 'Телосложение',
        'base.percipience'               => 'Восприятие',
        'base.charisma'                  => 'Харизма',
        'base.luck'                      => 'Удача',
        'defense.defense'                => 'Защита',
        'defense.magicDefense'           => 'Магическая защита',
        'defense.increaseDefense'        => 'Защита',
        'defense.increaseMagicDefense'   => 'Магическая защита',
        'offense.accuracy'               => 'Меткость',
        'offense.magicAccuracy'          => 'Магическая меткость',
        'offense.increaseAccuracy'       => 'Меткость',
        'offense.increaseMagicAccuracy'  => 'Магическая меткость',
        'offense.increaseAttackSpeed'    => 'Скорости атаки',
        'offense.increaseCastSpeed'      => 'Скорости создания заклинаний',
        'offense.increaseCriticalChance' => 'Шанса критического удара',
        'offense.blockIgnore'            => 'Игнорирование блока цели',
        'base.stamina'                   => 'Выносливость',
        'base.maxHorror'                 => 'Максимум ужаса',
        'base.lifeRegen'                 => 'Восстановление здоровья',
        'base.manaRegen'                 => 'Восстановление маны',
        'base.staminaCost'               => 'Расход выносливости',
        'defense.physicalMaxResist'      => 'Максимальное сопротивление физическому урону',
        'defense.fireMaxResist'          => 'Максимальное сопротивление урону огнем',
        'defense.waterMaxResist'         => 'Максимальное сопротивление урону водой',
        'defense.airMaxResist'           => 'Максимальное сопротивление урону воздухом',
        'defense.earthMaxResist'         => 'Максимальное сопротивление урону землей',
        'defense.lifeMaxResist'          => 'Максимальное сопротивление урону магии жизни',
        'defense.deathMaxResist'         => 'Максимальное сопротивление урону магии смерти',
        'defense.allMaxResist'           => 'Все максимальные сопротивления',
        'defense.block'                  => 'Блок',
        'defense.magicBlock'             => 'Магический блок',
        'defense.bonusHidden'            => 'Бонус к скрытности',
        'base.increaseGold'              => 'Бонус к получаемому золоту',
        'offense.damageMultiplier'       => 'Множитель урона',
        'base.increaseLife'              => 'Здоровье',
        'base.increaseMana'              => 'Мана',
        'base.bonusConcentration'        => 'Бонус к получаемой концентрации',
        'base.bonusRage'                 => 'Бонус к получаемой ярости',
        'base.bonusCunning'              => 'Бонус к хитрости',
        'base.beltSlot'                  => 'Мест в поясе',
        'Min strength'                   => 'Необходимо силы',
        'Min dexterity'                  => 'Необходимо ловкости',
        'Min intelligence'               => 'Необходимо интеллекта',

        // quality
        'broken_m'                       => 'Сломанный',
        'broken_f'                       => 'Сломанная',
        'broken_n'                       => 'Сломанное',
        'broken_p'                       => 'Сломанные',
        'low_quality_m'                  => 'Низкокачественный',
        'low_quality_f'                  => 'Низкокачественная',
        'low_quality_n'                  => 'Низкокачественное',
        'low_quality_p'                  => 'Низкокачественные',
        'rude_m'                         => 'Грубый',
        'rude_f'                         => 'Грубая',
        'rude_n'                         => 'Грубое',
        'rude_p'                         => 'Грубые',
        'good_quality_m'                 => 'Добротный',
        'good_quality_f'                 => 'Добротная',
        'good_quality_n'                 => 'Добротное',
        'good_quality_p'                 => 'Добротные',
        'qualitative_m'                  => 'Качественный',
        'qualitative_f'                  => 'Качественная',
        'qualitative_n'                  => 'Качественное',
        'qualitative_p'                  => 'Качественные',
        'excellent_m'                    => 'Превосходный',
        'excellent_f'                    => 'Превосходная',
        'excellent_n'                    => 'Превосходное',
        'excellent_p'                    => 'Превосходные',
        'fabulous_m'                     => 'Великолепный',
        'fabulous_f'                     => 'Великолепная',
        'fabulous_n'                     => 'Великолепное',
        'fabulous_p'                     => 'Великолепные',
        'unrivaled_m'                    => 'Непревзойденный',
        'unrivaled_f'                    => 'Непревзойденная',
        'unrivaled_n'                    => 'Непревзойденное',
        'unrivaled_p'                    => 'Непревзойденные',

        // materials metal
        'copper_m'                       => 'Медный',
        'copper_f'                       => 'Медная',
        'copper_n'                       => 'Медное',
        'copper_p'                       => 'Медные',
        'iron_m'                         => 'Железный',
        'iron_f'                         => 'Железная',
        'iron_n'                         => 'Железное',
        'iron_p'                         => 'Железные',
        'silver_m'                       => 'Серебряный',
        'silver_f'                       => 'Серебряная',
        'silver_n'                       => 'Серебряное',
        'silver_p'                       => 'Серебряные',
        'gold_m'                         => 'Золотой',
        'gold_f'                         => 'Золотая',
        'gold_n'                         => 'Золотое',
        'gold_p'                         => 'Золотые',
        'agatyp_m'                       => 'Агатиповый',
        'agatyp_f'                       => 'Агатиповая',
        'agatyp_n'                       => 'Агатиповое',
        'agatyp_p'                       => 'Агатиповые',
        'white_metal_m'                  => 'Белый',
        'white_metal_f'                  => 'Белая',
        'white_metal_n'                  => 'Белое',
        'white_metal_p'                  => 'Белые',
        'miteril_m'                      => 'Митериловый',
        'miteril_f'                      => 'Митериловая',
        'miteril_n'                      => 'Митериловое',
        'miteril_p'                      => 'Митериловые',
        'doom_metal_m'                   => 'Смертельный',
        'doom_metal_f'                   => 'Смертельная',
        'doom_metal_n'                   => 'Смертельное',
        'doom_metal_p'                   => 'Смертельные',
        'crystalline_metal_m'            => 'Кристальный',
        'crystalline_metal_f'            => 'Кристальная',
        'crystalline_metal_n'            => 'Кристальное',
        'crystalline_metal_p'            => 'Кристальные',
        'meteorite_m'                    => 'Метеоритовый',
        'meteorite_f'                    => 'Метеоритовая',
        'meteorite_n'                    => 'Метеоритовое',
        'meteorite_p'                    => 'Метеоритовые',
        'mithril_m'                      => 'Мифриловый',
        'mithril_f'                      => 'Мифриловая',
        'mithril_n'                      => 'Мифриловое',
        'mithril_p'                      => 'Мифриловые',
        'valorite_m'                     => 'Валоритовый',
        'valorite_f'                     => 'Валоритовая',
        'valorite_n'                     => 'Валоритовое',
        'valorite_p'                     => 'Валоритовые',
        'verite_m'                       => 'Веритовый',
        'verite_f'                       => 'Веритовая',
        'verite_n'                       => 'Веритовое',
        'verite_p'                       => 'Веритовые',
        'black_metal_m'                  => 'Черный',
        'black_metal_f'                  => 'Черная',
        'black_metal_n'                  => 'Черное',
        'black_metal_p'                  => 'Черные',
        'heavenly_metal_m'               => 'Небесный',
        'heavenly_metal_f'               => 'Небесная',
        'heavenly_metal_n'               => 'Небесное',
        'heavenly_metal_p'               => 'Небесные',
        'titan_m'                        => 'Титановый',
        'titan_f'                        => 'Титановая',
        'titan_n'                        => 'Титановое',
        'titan_p'                        => 'Титановые',

        // materials woods
        'mahogany_m'                     => 'из Красного дерева',
        'mahogany_f'                     => 'из Красного дерева',
        'mahogany_n'                     => 'из Красного дерева',
        'mahogany_p'                     => 'из Красного дерева',
        'merbau_tree_m'                  => 'из дерева Мербау',
        'merbau_tree_f'                  => 'из дерева Мербау',
        'merbau_tree_n'                  => 'из дерева Мербау',
        'merbau_tree_p'                  => 'из дерева Мербау',
        'amaranth_tree_m'                => 'из Амарантового дерева',
        'amaranth_tree_f'                => 'из Амарантового дерева',
        'amaranth_tree_n'                => 'из Амарантового дерева',
        'amaranth_tree_p'                => 'из Амарантового дерева',
        'oak_m'                          => 'из Дуба',
        'oak_f'                          => 'из Дуба',
        'oak_n'                          => 'из Дуба',
        'oak_p'                          => 'из Дуба',
        'sacred_tree_m'                  => 'из Священного дерева',
        'sacred_tree_f'                  => 'из Священного дерева',
        'sacred_tree_n'                  => 'из Священного дерева',
        'sacred_tree_p'                  => 'из Священного дерева',
        'bloody_tree_m'                  => 'из Кровавого дерева',
        'bloody_tree_f'                  => 'из Кровавого дерева',
        'bloody_tree_n'                  => 'из Кровавого дерева',
        'bloody_tree_p'                  => 'из Кровавого дерева',
        'sequoia_m'                      => 'из Секвойи',
        'sequoia_f'                      => 'из Секвойи',
        'sequoia_n'                      => 'из Секвойи',
        'sequoia_p'                      => 'из Секвойи',
        'ruby_tree_m'                    => 'из Рубинового дерева',
        'ruby_tree_f'                    => 'из Рубинового дерева',
        'ruby_tree_n'                    => 'из Рубинового дерева',
        'ruby_tree_p'                    => 'из Рубинового дерева',
        'juniper_m'                      => 'из Можжевелового дерева',
        'juniper_f'                      => 'из Можжевелового дерева',
        'juniper_n'                      => 'из Можжевелового дерева',
        'juniper_p'                      => 'из Можжевелового дерева',
        'sakura_m'                       => 'из Сакуры',
        'sakura_f'                       => 'из Сакуры',
        'sakura_n'                       => 'из Сакуры',
        'sakura_p'                       => 'из Сакуры',
        'mangrove_tree_m'                => 'из Мангрового дерева',
        'mangrove_tree_f'                => 'из Мангрового дерева',
        'mangrove_tree_n'                => 'из Мангрового дерева',
        'mangrove_tree_p'                => 'из Мангрового дерева',
        'poisonous_tree_m'               => 'из Ядовитого дерева',
        'poisonous_tree_f'               => 'из Ядовитого дерева',
        'poisonous_tree_n'               => 'из Ядовитого дерева',
        'poisonous_tree_p'               => 'из Ядовитого дерева',
        'wisteria_m'                     => 'из Глицинии',
        'wisteria_f'                     => 'из Глицинии',
        'wisteria_n'                     => 'из Глицинии',
        'wisteria_p'                     => 'из Глицинии',
        'thousand_year_tree_m'           => 'из Тысячелетнего дерева',
        'thousand_year_tree_f'           => 'из Тысячелетнего дерева',
        'thousand_year_tree_n'           => 'из Тысячелетнего дерева',
        'thousand_year_tree_p'           => 'из Тысячелетнего дерева',

        // materials leather
        'wolf_leather_m'                 => 'из кожи волка',
        'wolf_leather_f'                 => 'из кожи волка',
        'wolf_leather_n'                 => 'из кожи волка',
        'wolf_leather_p'                 => 'из кожи волка',
        'hyena_leather_m'                => 'из кожи гиены',
        'hyena_leather_f'                => 'из кожи гиены',
        'hyena_leather_n'                => 'из кожи гиены',
        'hyena_leather_p'                => 'из кожи гиены',
        'scavenger_leather_m'            => 'из кожи падальщика',
        'scavenger_leather_f'            => 'из кожи падальщика',
        'scavenger_leather_n'            => 'из кожи падальщика',
        'scavenger_leather_p'            => 'из кожи падальщика',
        'griffin_leather_m'              => 'из кожи грифона',
        'griffin_leather_f'              => 'из кожи грифона',
        'griffin_leather_n'              => 'из кожи грифона',
        'griffin_leather_p'              => 'из кожи грифона',
        'boar_leather_m'                 => 'из кожи кабана',
        'boar_leather_f'                 => 'из кожи кабана',
        'boar_leather_n'                 => 'из кожи кабана',
        'boar_leather_p'                 => 'из кожи кабана',
        'white_deer_leather_m'           => 'из кожи белого оленя',
        'white_deer_leather_f'           => 'из кожи белого оленя',
        'white_deer_leather_n'           => 'из кожи белого оленя',
        'white_deer_leather_p'           => 'из кожи белого оленя',
        'monitor_lizard_leather_m'       => 'из кожи варана',
        'monitor_lizard_leather_f'       => 'из кожи варана',
        'monitor_lizard_leather_n'       => 'из кожи варана',
        'monitor_lizard_leather_p'       => 'из кожи варана',
        'bison_leather_m'                => 'из кожи бизона',
        'bison_leather_f'                => 'из кожи бизона',
        'bison_leather_n'                => 'из кожи бизона',
        'bison_leather_p'                => 'из кожи бизона',
        'leopard_leather_m'              => 'из кожи леопарда',
        'leopard_leather_f'              => 'из кожи леопарда',
        'leopard_leather_n'              => 'из кожи леопарда',
        'leopard_leather_p'              => 'из кожи леопарда',
        'hippopotamus_leather_m'         => 'из кожи бегемота',
        'hippopotamus_leather_f'         => 'из кожи бегемота',
        'hippopotamus_leather_n'         => 'из кожи бегемота',
        'hippopotamus_leather_p'         => 'из кожи бегемота',
        'irbis_leather_m'                => 'из кожи барса',
        'irbis_leather_f'                => 'из кожи барса',
        'irbis_leather_n'                => 'из кожи барса',
        'irbis_leather_p'                => 'из кожи барса',
        'bear_leather_m'                 => 'из кожи медведя',
        'bear_leather_f'                 => 'из кожи медведя',
        'bear_leather_n'                 => 'из кожи медведя',
        'bear_leather_p'                 => 'из кожи медведя',
        'royal_fox_leather_m'            => 'из кожи королевского лиса',
        'royal_fox_leather_f'            => 'из кожи королевского лиса',
        'royal_fox_leather_n'            => 'из кожи королевского лиса',
        'royal_fox_leather_p'            => 'из кожи королевского лиса',
        'rakshasa_leather_m'             => 'из кожи ракшаса',
        'rakshasa_leather_f'             => 'из кожи ракшаса',
        'rakshasa_leather_n'             => 'из кожи ракшаса',
        'rakshasa_leather_p'             => 'из кожи ракшаса',
        'wyvern_leather_m'               => 'из кожи виверны',
        'wyvern_leather_f'               => 'из кожи виверны',
        'wyvern_leather_n'               => 'из кожи виверны',
        'wyvern_leather_p'               => 'из кожи виверны',
        'manticore_leather_m'            => 'из кожи мантикоры',
        'manticore_leather_f'            => 'из кожи мантикоры',
        'manticore_leather_n'            => 'из кожи мантикоры',
        'manticore_leather_p'            => 'из кожи мантикоры',
        'chimera_leather_m'              => 'из кожи химеры',
        'chimera_leather_f'              => 'из кожи химеры',
        'chimera_leather_n'              => 'из кожи химеры',
        'chimera_leather_p'              => 'из кожи химеры',
        'harpy_leather_m'                => 'из кожи гарпии',
        'harpy_leather_f'                => 'из кожи гарпии',
        'harpy_leather_n'                => 'из кожи гарпии',
        'harpy_leather_p'                => 'из кожи гарпии',
        'cave_snake_leather_m'           => 'из кожи пещерного змея',
        'cave_snake_leather_f'           => 'из кожи пещерного змея',
        'cave_snake_leather_n'           => 'из кожи пещерного змея',
        'cave_snake_leather_p'           => 'из кожи пещерного змея',
        'unicorn_leather_m'              => 'из кожи единорога',
        'unicorn_leather_f'              => 'из кожи единорога',
        'unicorn_leather_n'              => 'из кожи единорога',
        'unicorn_leather_p'              => 'из кожи единорога',
        'night_beast_leather_m'          => 'из кожи ночной твари',
        'night_beast_leather_f'          => 'из кожи ночной твари',
        'night_beast_leather_n'          => 'из кожи ночной твари',
        'night_beast_leather_p'          => 'из кожи ночной твари',
        'elephant_leather_m'             => 'из кожи слона',
        'elephant_leather_f'             => 'из кожи слона',
        'elephant_leather_n'             => 'из кожи слона',
        'elephant_leather_p'             => 'из кожи слона',

        // materials fabric
        'ajura_fabric_m'                 => 'из Ажура',
        'ajura_fabric_f'                 => 'из Ажура',
        'ajura_fabric_n'                 => 'из Ажура',
        'ajura_fabric_p'                 => 'из Ажура',
        'aksamit_fabric_m'               => 'из Аксамита',
        'aksamit_fabric_f'               => 'из Аксамита',
        'aksamit_fabric_n'               => 'из Аксамита',
        'aksamit_fabric_p'               => 'из Аксамита',
        'altabas_fabric_m'               => 'из Алтабаса',
        'altabas_fabric_f'               => 'из Алтабаса',
        'altabas_fabric_n'               => 'из Алтабаса',
        'altabas_fabric_p'               => 'из Алтабаса',
        'barezh_fabric_m'                => 'из Барежа',
        'barezh_fabric_f'                => 'из Барежа',
        'barezh_fabric_n'                => 'из Барежа',
        'barezh_fabric_p'                => 'из Барежа',
        'velvet_fabric_m'                => 'из Бархата',
        'velvet_fabric_f'                => 'из Бархата',
        'velvet_fabric_n'                => 'из Бархата',
        'velvet_fabric_p'                => 'из Бархата',
        'velour_fabric_m'                => 'из Велюра',
        'velour_fabric_f'                => 'из Велюра',
        'velour_fabric_n'                => 'из Велюра',
        'velour_fabric_p'                => 'из Велюра',
        'cashmere_fabric_m'              => 'из Кашемира Алмафеи',
        'cashmere_fabric_f'              => 'из Кашемира Алмафеи',
        'cashmere_fabric_n'              => 'из Кашемира Алмафеи',
        'cashmere_fabric_p'              => 'из Кашемира Алмафеи',
        'elven_flannel_fabric_m'         => 'из Эльфийской Фланели',
        'elven_flannel_fabric_f'         => 'из Эльфийской Фланели',
        'elven_flannel_fabric_n'         => 'из Эльфийской Фланели',
        'elven_flannel_fabric_p'         => 'из Эльфийской Фланели',
        'merino_wool_fabric_m'           => 'из Шерсти Мериноса',
        'merino_wool_fabric_f'           => 'из Шерсти Мериноса',
        'merino_wool_fabric_n'           => 'из Шерсти Мериноса',
        'merino_wool_fabric_p'           => 'из Шерсти Мериноса',
        'siren_satin_fabric_m'           => 'из Сатина Сирены',
        'siren_satin_fabric_f'           => 'из Сатина Сирены',
        'siren_satin_fabric_n'           => 'из Сатина Сирены',
        'siren_satin_fabric_p'           => 'из Сатина Сирены',
        'crimson_visson_fabric_m'        => 'из Багрового Виссона',
        'crimson_visson_fabric_f'        => 'из Багрового Виссона',
        'crimson_visson_fabric_n'        => 'из Багрового Виссона',
        'crimson_visson_fabric_p'        => 'из Багрового Виссона',

        // items
        // crossbow
        'Light Crossbow'                 => 'Легкий Арбалет',
        'Militiaman‘s Crossbow'          => 'Арбалет Ополченца',
        'Heavy crossbow'                 => 'Тяжелый Арбалет',
        'Arquebus'                       => 'Аркебуз',
        'Crossbow'                       => 'Арбалет',
        'Double crossbow'                => 'Сдвоенный Арбалет',
        'Self-loading crossbow'          => 'Самострел',
        'Siege Crossbow'                 => 'Осадный Арбалет',
        'Double Heavy Crossbow'          => 'Сдвоенный Тяжелый Арбалет',
        'Rapid Fire Crossbow'            => 'Скорострельный Арбалет',
        'Dwarven Crossbow'               => 'Гномский Арбалет',
        'Scourge of Magicians'           => 'Бич Магов',
        'Compound crossbow'              => 'Блочный Арбалет',
        'The Storm of Knights'           => 'Гроза Рыцарей',
        'Ballista'                       => 'Баллиста',
        'Multi-shot crossbow'            => 'Многозарядный Арбалет',
        'Hydra Crossbow'                 => 'Арбалет Гидры',
        'Dragon Slayer'                  => 'Убийца Драконов',
        // bow
        'Longbow'                        => 'Длинный Лук',
        'Composite Bow'                  => 'Композитный Лук',
        'War Longbow'                    => 'Боевой длинный Лук',
        'Elven Bow'                      => 'Эльфийский Лук',
        'Amazon Bow'                     => 'Лук Амазонки',
        'Royal Bow'                      => 'Королевский Лук',
        'Short Bow'                      => 'Короткий Лук',
        'Hunting Bow'                    => 'Охотничий Лук',
        'Carved Bow'                     => 'Резной Лук',
        'Compound Bow'                   => 'Блочный Лук',
        'Soul Piercer'                   => 'Пронзатель Душ',
        'Bow of the Night'               => 'Лук Ночи',
        // staff
        'Staff'                          => 'Посох',
        'Carved Staff'                   => 'Резной Посох',
        'Ruby Staff'                     => 'Рубиновый Посох',
        'War Staff'                      => 'Боевой Посох',
        'Elven Staff'                    => 'Эльфийский Посох',
        'Arbiter of Fates'               => 'Вершитель Судеб',
        // wands
        'Disciple‘s Rod'                 => 'Жезл Ученика',
        'Magic Wand'                     => 'Магическая Палочка',
        'Wand of Elements'               => 'Жезл Стихий',
        'Wizard‘s Wand'                  => 'Жезл Чародея',
        'Rod of Wisdom'                  => 'Жезл Мудрости',
        'Phoenix Wand'                   => 'Жезл Феникса',
        // dagger
        'Knife'                          => 'Нож',
        'Dagger'                         => 'Кинжал',
        'Stylet'                         => 'Стилет',
        'Sting'                          => 'Жало',
        'Thief‘s Dagger'                 => 'Кинжал Вора',
        'Dirk'                           => 'Кортик',
        // sword one hand
        'Short Sword'                    => 'Короткий Меч',
        'Saber'                          => 'Сабля',
        'Gladius'                        => 'Гладиус',
        'Sword of Wanderer'              => 'Меч Странника',
        'Katana'                         => 'Катана',
        'Knight‘s Sword'                 => 'Рыцарский Меч',
        // sword two hand
        'Two-handed Sword'               => 'Двуручный Меч',
        'Claymore'                       => 'Клеймор',
        'Flamberg'                       => 'Фламберг',
        'Espadon'                        => 'Эспадон',
        'Zweihander'                     => 'Цвайхандер',
        'Caliburs'                       => 'Эскалибур',
        // sword heavy one hand
        'Heavy Sword'                    => 'Тяжелый Меч',
        'Jagged Sword'                   => 'Зазубренный Меч',
        'Sword of Renegade'              => 'Меч отступника',
        'Scimitar'                       => 'Ятаган',
        'Shamshir'                       => 'Шамшир',
        'Bloodsucker'                    => 'Кровопийца',
        // sword heavy two hand
        'Great Sword'                    => 'Большой Меч',
        'Cleaver'                        => 'Разрубатель',
        'Sword of Cutthroat'             => 'Меч Головореза',
        'Blade of Giant'                 => 'Клинок Гиганта',
        'Armor Breaker'                  => 'Крушитель доспехов',
        'Sword of Darkness'              => 'Меч Тьмы',
        // axe one hand
        'Lumberjack‘s Axe'               => 'Топор Лесоруба',
        'Battle Axe'                     => 'Боевой Топор',
        'Northern Axe'                   => 'Северный Топор',
        'Dwarven Axe'                    => 'Гномский Топор',
        'Tomahawk'                       => 'Томагавк',
        'Berserker Axe'                  => 'Топор Берсерка',
        // axe two hand
        'Two-handed Axe'                 => 'Двуручный Топор',
        'Cleaver Axe'                    => 'Колун',
        'Broad Axe'                      => 'Широкий Топор',
        'Axe'                            => 'Секира',
        'Executioner‘s Axe'              => 'Топор Палача',
        'Gothic Axe'                     => 'Готический Топор',
        // axe heavy one hand
        'Heavy Axe'                      => 'Тяжелый Топор',
        'Jagged Axe'                     => 'Зазубренный Топор',
        'Heavy Battle Axe'               => 'Тяжелый Боевой Топор',
        'Chopper'                        => 'Рубило',
        'Deadman‘s Glory'                => 'Топор Мертвеца',
        'Shieldbreaker'                  => 'Разрубатель Щитов',
        // axe heavy two hand
        'Heavy Cleaver'                  => 'Тяжелый Колун',
        'Ogre Axe'                       => 'Топор Орга',
        'Heavy War Axe'                  => 'Тяжелый Топор Войны',
        'Skull Splitter'                 => 'Раскалыватель Черепов',
        'Cannibal‘s Axe'                 => 'Топор Людоеда',
        'Widowmaker'                     => 'Вдоводел',
        // mace one hand
        'Club'                           => 'Дубина',
        'Mace'                           => 'Булава',
        'Spiked Mace'                    => 'Булава с Шипами',
        'Flail'                          => 'Кистень',
        'Buzdygan'                       => 'Буздыган',
        'Angelic Wrath'                  => 'Ангельский Гнев',
        // mace two hand
        'Two-handed Cudgel'              => 'Двуручная Дубина',
        'Two-handed Hammer'              => 'Двуручный Молот',
        'Pood Hammer'                    => 'Пудовый Молот',
        'Two-handed Flail'               => 'Двуручный Кистень',
        'Hammer of Dwarves'              => 'Молот Гномов',
        'Messenger of Death'             => 'Вестник Смерти',
        // mace heavy one hand
        'Hammer'                         => 'Молот',
        'Blacksmith‘s Hammer'            => 'Молот Кузнеца',
        'War Hammer'                     => 'Боевой Молот',
        'Heavy Spiked Mace'              => 'Тяжелая Шипастая Булава',
        'Morning Star'                   => 'Утренняя Звезда',
        'Shepherd‘s Wrath'               => 'Гнев Пастыря',
        // mace heavy two hand
        'Heavy Two-Handed Hammer'        => 'Тяжелый Двуручный Молот',
        'Sledgehammer'                   => 'Кувалда',
        'Bonebreaker'                    => 'Костолом',
        'Hammer of Giants'               => 'Молот Гигантов',
        'Hammer of Death'                => 'Молот Смерти',
        'King‘s Hammer'                  => 'Королевский Молот',
        // body armor [robe]
        'Wanderer‘s Cape'                => 'Накидка Странника',
        'Cape of Adept'                  => 'Накидка Адепта',
        'Priest‘s Cape'                  => 'Накидка Священника',
        'Mage‘s Robe'                    => 'Одеяние Мага',
        'Elven Robe'                     => 'Одеяние Эльфов',
        'Robe of Wisdom'                 => 'Мантия Мудрости',
        // body armor [light]
        'Vest'                           => 'Жилет',
        'Jacket'                         => 'Куртка',
        'Thief‘s Jacket'                 => 'Куртка Вора',
        'Fur Armor'                      => 'Стеганый Доспех',
        'Riveted Breastplate'            => 'Проклепанный Нагрудник',
        'Armor of Oath'                  => 'Доспех Клятвы',
        // body armor [medium]
        'Chainmail'                      => 'Кольчуга',
        'Armor of Militia'               => 'Доспех Ополченца',
        'Riveted Chainmail'              => 'Клепанная Кольчуга',
        'Plate-shaped Armor'             => 'Пластинчатый Доспех',
        'Dwarven Armor'                  => 'Гномский Доспех',
        'Light Plate Armor'              => 'Легкий Латный Доспех',
        // body armor [heavy]
        'Chest Plate'                    => 'Нагрудная Пластина', // todo Нагрудник Шахтера
        'Blacksmith‘s Armor'             => 'Броня Кузнеца',
        'Guardian Armor'                 => 'Доспех Стражника',
        'Orc Armor'                      => 'Орочья Броня',
        'Knight‘s Cuirass'               => 'Рыцарская Кираса',
        'Plate Armor'                    => 'Латный Доспех',
        // helmet [robe]
        'Wanderer‘s Hat'                 => 'Шляпа Странника',
        'Adept‘s Hood'                   => 'Капюшон Адепта',
        'Priest‘s Hood'                  => 'Капюшон Священника',
        'Mage‘s Hood'                    => 'Капюшон Мага',
        'Elven Hood'                     => 'Капюшон Эльфов',
        'Hood of Wisdom'                 => 'Капюшон Мудрости',
        // helmet [light]
        'Cap'                            => 'Шапка',
        'Helmet'                         => 'Шлем',
        'Thief‘s Helmet'                 => 'Шлем Вора',
        'Quilted Helmet'                 => 'Стеганый Шлем',
        'Cursed Helmet'                  => 'Проклятый Шлем',
        'Helmet of Oath'                 => 'Шлем Клятвы',
        // helmet [medium]
        'Chainmail Helmet'               => 'Кольчужный Шлем',
        'Militiaman‘s Helmet'            => 'Шлем Ополченца',
        'Riveted Chainmail Helmet'       => 'Клепанный Кольчужный Шлем',
        'Full Helmet'                    => 'Полный Шлем',
        'Dwarven Helmet'                 => 'Гномский Шлем',
        'Light Plate Helmet'             => 'Легкий Латный Шлем',
        // helmet [heavy]
        'Miner‘s Helmet'                 => 'Каска Шахтера',
        'Blacksmith‘s Helmet'            => 'Шлем Кузнеца',
        'Guardian Helmet'                => 'Шлем Стражника',
        'Orc Helmet'                     => 'Орочий Шлем',
        'Knight‘s Helmet'                => 'Рыцарский Шлем',
        'Plate Helmet'                   => 'Латный Шлем',
        // gloves [robe]
        'Wanderer‘s Gloves'              => 'Перчатки Странника',
        'Adept Gloves'                   => 'Перчатки Адепта',
        'Priest‘s Gloves'                => 'Перчатки Священника',
        'Magician‘s Gloves'              => 'Перчатки Мага',
        'Elven Gloves'                   => 'Эльфийские Перчатки',
        'Gloves of Wisdom'               => 'Перчатки Мудрости',
        // gloves [light]
        'Gloves'                         => 'Перчатки',
        'Mittens'                        => 'Рукавицы',
        'Thief‘s Gloves'                 => 'Перчатки Вора',
        'Quilted Gloves'                 => 'Стеганые Перчатки',
        'Cursed Gloves'                  => 'Проклятые Перчатки',
        'Gloves of Oath'                 => 'Перчатки Клятвы',
        // gloves [medium]
        'Chainmail Gloves'               => 'Кольчужные Перчатки',
        'Militia Gloves'                 => 'Перчатки Ополченца',
        'Riveted Chainmail Gloves'       => 'Клепаные Кольчужные Перчатки',
        'Forged Gloves'                  => 'Кованные Перчатки',
        'Dwarven Gloves'                 => 'Перчатки Гномов',
        'Light Plate Gloves'             => 'Легкие Латные Перчатки',
        // gloves [heavy]
        'Miner‘s Gloves'                 => 'Шахтерские Перчатки',
        'Blacksmith‘s Gloves'            => 'Перчатки Кузнеца',
        'Guardian Gloves'                => 'Перчатки Стражника',
        'Orc Gloves'                     => 'Орочьи Перчатки',
        'Knight‘s Gloves'                => 'Рыцарские Перчатки',
        'Plate Gloves'                   => 'Латные Перчатки',
        // boots [robe]
        'Wanderer‘s Shoes'               => 'Обувь Странника',
        'Adept Shoes'                    => 'Обувь Адепта',
        'Priest‘s Shoes'                 => 'Обувь Священника',
        'Magician‘s Shoes'               => 'Обувь Мага',
        'Elven Shoes'                    => 'Эльфийские Туфли',
        'Boots of Wisdom'                => 'Сапоги Мудрости',
        // boots [light]
        'Footcloths'                     => 'Портянки',
        'Boots'                          => 'Сапоги',
        'Thief‘s Boots'                  => 'Сапоги Вора',
        'Quilted Boots'                  => 'Стеганые Сапоги',
        'Cursed Boots'                   => 'Проклятые Сапоги',
        'Boots of Oath'                  => 'Сапоги Клятвы',
        // boots [medium]
        'Chainmail Boots'                => 'Кольчужные Сапоги',
        'Militiaman‘s Boots'             => 'Сапоги Ополченца',
        'Riveted Chainmail Boots'        => 'Клепаные Кольчужные Сапоги',
        'Forged Boots'                   => 'Кованные Сапоги',
        'Dwarven Boots'                  => 'Сапоги Гномов',
        'Light Plate Boots'              => 'Легкие Латные Сапоги',
        // boots [heavy]
        'Miner‘s Boots'                  => 'Шахтерские Сапоги',
        'Blacksmith‘s Boots'             => 'Сапоги Кузнеца',
        'Guard Boots'                    => 'Сапоги Стражника',
        'Orc Boots'                      => 'Орочьи Сапоги',
        'Knight‘s Boots'                 => 'Рыцарские Сапоги',
        'Plate Boots'                    => 'Латные Сапоги',
        // legs [robe]
        'Wanderer Belt'                  => 'Пояс Странника',
        'Adept Belt'                     => 'Пояс Адепта',
        'Priest‘s Belt'                  => 'Пояс Священника',
        'Magician‘s Belt'                => 'Пояс Мага',
        'Elven Pants'                    => 'Эльфийские Штаны',
        'Pants of Wisdom'                => 'Штаны Мудрости',
        // legs [light]
        'Trousers'                       => 'Штаны',
        'Legguards'                      => 'Набедренники',
        'Thief‘s Pants'                  => 'Штаны Вора',
        'Quilted Pants'                  => 'Стеганые Штаны',
        'Cursed Pants'                   => 'Проклятые Штаны',
        'Oath Pants'                     => 'Штаны Клятвы',
        // legs [medium]
        'Chainmail Pants'                => 'Кольчужные Штаны',
        'Militiaman‘s Pants'             => 'Штаны Ополченца',
        'Riveted Chainmail Pants'        => 'Клепаные Кольчужные Штаны',
        'Forged Leggings'                => 'Кованные Поножи',
        'Dwarven Leggings'               => 'Поножи Гномов',
        'Light Plate Greaves'            => 'Легкие Латные Поножи',
        // legs [heavy]
        'Miner‘s Leggings'               => 'Шахтерские Поножи',
        'Blacksmith‘s Leggings'          => 'Поножи Кузнеца',
        'Guard‘s Leggings'               => 'Поножи Стражника',
        'Orc Leggings'                   => 'Орочьи Поножи',
        'Knight‘s Leggings'              => 'Рыцарские Поножи',
        'Plate Leggings'                 => 'Латные Поножи',
        // shoulders [robe]
        'Wanderer‘s Armlets'             => 'Нарукавники Странника',
        'Adept‘s Armbands'               => 'Нарукавники Адепта',
        'Priest‘s Armbands'              => 'Нарукавники Священника',
        'Magician‘s Armbands'            => 'Нарукавники Мага',
        'Elven Armbands'                 => 'Эльфийские Нарукавники',
        'Armbands of Wisdom'             => 'Нарукавники Мудрости',
        // shoulders [light]
        'Armbands'                       => 'Нарукавники',
        'Shoulders'                      => 'Наплечники',
        'Thief‘s Shoulders'              => 'Наплечники Вора',
        'Quilted Shoulders'              => 'Стеганые Наплечники',
        'Cursed Shoulders'               => 'Проклятые Наплечники',
        'Shoulders of Oath'              => 'Наплечники Клятвы',
        // shoulders [medium]
        'Chainmail Armlets'              => 'Кольчужные Нарукавники',
        'Militiaman‘s Shoulders'         => 'Наплечники Ополченца',
        'Riveted Chainmail Shoulders'    => 'Клепаные Кольчужные Наплечники',
        'Forged Shoulders'               => 'Кованные Наплечники',
        'Dwarven Shoulders'              => 'Наплечники Гномов',
        'Light Plate Shoulders'          => 'Легкие Латные Наплечники',
        // shoulders [heavy]
        'Miner‘s Shoulders'              => 'Шахтерские Наплечники',
        'Blacksmith‘s Shoulders'         => 'Наплечники Кузнеца',
        'Guard‘s Shoulders'              => 'Наплечники Стражника',
        'Orc Shoulders'                  => 'Орочьи Наплечники',
        'Knight‘s Shoulders'             => 'Рыцарские Наплечники',
        'Plate Shoulders'                => 'Латные Наплечники',
        // shield
        'Round Shield'                   => 'Круглый Щит',
        'Militiaman‘s Shield'            => 'Щит Ополченца',
        'Teardrop Shield'                => 'Каплевидный Щит',
        'Dwarven Shield'                 => 'Щит Гномов',
        'Knight‘s Shield'                => 'Рыцарский Щит',
        'Gothic Shield'                  => 'Готический Щит',
        // ring
        'Ring'                           => 'Кольцо',
        'Ring with Pearl'                => 'Кольцо с Жемчужиной',
        'Ring with Ruby'                 => 'Кольцо с Рубином',
        'Ring with Amber'                => 'Кольцо с Янтарем',
        'Ring of Moon'                   => 'Кольцо Луны',
        'Ring of Wisdom'                 => 'Кольцо Мудрости',
        // amulet
        'Amulet'                         => 'Амулет',
        'Priest‘s Necklace'              => 'Ожерелье Священника',
        'Amulet of Sun'                  => 'Амулет Солнца',
        'Amulet with Sapphire'           => 'Амулет с Сапфиром',
        'Amulet of Necromancer'          => 'Амулет Некроманта',
        'Amulet of Wisdom'               => 'Амулет Мудрости',
    ];

    /**
     * @param string $string
     * @return string
     */
    public function trans(string $string): string
    {
        if (array_key_exists($string, self::$lang)) {
            return self::$lang[$string];
        }

        return $string;
    }
}
