<?php

declare(strict_types=1);

namespace Item\Material\DataProvider;

use Item\Material\Element\MaterialElement;
use Item\Type\Material\MaterialTypeInterface;

class Leather extends AbstractMaterialDataProvider
{
    protected static array $materials = [
        // Tier 1
        'wolf_leather'           => [
            'name'    => 'Wolf Leather',
            'icon'    => '/icon/leathers/leather_1.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 1,
            'quality' => 0.9,
            'prefix'  => '',
            'suffix'  => 'wolf_leather',
            'element' => MaterialElement::PHYSICAL,
        ],
        'hyena_leather'          => [
            'name'    => 'Hyena Leather',
            'icon'    => '/icon/leathers/leather_2.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 1,
            'quality' => 1.0,
            'prefix'  => '',
            'suffix'  => 'hyena_leather',
            'element' => MaterialElement::FIRE,
        ],
        'scavenger_leather'      => [
            'name'    => 'Scavenger Leather',
            'icon'    => '/icon/leathers/leather_21.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 3,
            'quality' => 1.1,
            'prefix'  => '',
            'suffix'  => 'scavenger_leather',
            'element' => MaterialElement::WATER,
        ],
        // Tier 2 [quality 1.2+]
        'griffin_leather'        => [
            'name'    => 'Griffin Leather',
            'icon'    => '/icon/leathers/leather_19.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 4,
            'quality' => 1.2,
            'prefix'  => '',
            'suffix'  => 'griffin_leather',
            'element' => MaterialElement::AIR,
        ],
        'boar_leather'           => [
            'name'    => 'Boar Leather',
            'icon'    => '/icon/leathers/leather_9.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 6,
            'quality' => 1.3,
            'prefix'  => '',
            'suffix'  => 'boar_leather',
            'element' => MaterialElement::EARTH,
        ],
        'white_deer_leather'     => [
            'name'    => 'White Deer Leather',
            'icon'    => '/icon/leathers/leather_10.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 8,
            'quality' => 1.4,
            'prefix'  => '',
            'suffix'  => 'white_deer_leather',
            'element' => MaterialElement::LIFE,
        ],
        'monitor_lizard_leather' => [
            'name'    => 'Monitor Lizard Leather',
            'icon'    => '/icon/leathers/leather_22.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 11,
            'quality' => 1.4,
            'prefix'  => '',
            'suffix'  => 'monitor_lizard_leather',
            'element' => MaterialElement::DEATH,
        ],
        // Tier 3 [quality 1.5+]
        'bison_leather'          => [
            'name'    => 'Bison Leather',
            'icon'    => '/icon/leathers/leather_9.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 14,
            'quality' => 1.5,
            'prefix'  => '',
            'suffix'  => 'bison_leather',
            'element' => MaterialElement::PHYSICAL,
        ],
        'leopard_leather'        => [
            'name'    => 'Leopard Leather',
            'icon'    => '/icon/leathers/leather_6.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 15,
            'quality' => 1.55,
            'prefix'  => '',
            'suffix'  => 'leopard_leather',
            'element' => MaterialElement::FIRE,
        ],
        'hippopotamus_leather'   => [
            'name'    => 'Hippopotamus Leather',
            'icon'    => '/icon/leathers/leather_17.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 16,
            'quality' => 1.6,
            'prefix'  => '',
            'suffix'  => 'hippopotamus_leather',
            'element' => MaterialElement::WATER,
        ],
        'irbis_leather'          => [
            'name'    => 'Irbis Leather',
            'icon'    => '/icon/leathers/leather_7.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 17,
            'quality' => 1.65,
            'prefix'  => '',
            'suffix'  => 'irbis_leather',
            'element' => MaterialElement::AIR,
        ],
        'bear_leather'           => [
            'name'    => 'Bear Leather',
            'icon'    => '/icon/leathers/leather_18.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 18,
            'quality' => 1.7,
            'prefix'  => '',
            'suffix'  => 'bear_leather',
            'element' => MaterialElement::EARTH,
        ],
        'royal_fox_leather'      => [
            'name'    => 'Royal Fox Leather',
            'icon'    => '/icon/leathers/leather_20.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 20,
            'quality' => 1.75,
            'prefix'  => '',
            'suffix'  => 'royal_fox_leather',
            'element' => MaterialElement::LIFE,
        ],
        'rakshasa_leather'       => [
            'name'    => 'Rakshasa Leather',
            'icon'    => '/icon/leathers/leather_22.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 21,
            'quality' => 1.75,
            'prefix'  => '',
            'suffix'  => 'rakshasa_leather',
            'element' => MaterialElement::DEATH,
        ],
        'wyvern_leather'       => [
            'name'    => 'Wyvern Leather',
            'icon'    => '/icon/leathers/leather_21.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 22,
            'quality' => 1.75,
            'prefix'  => '',
            'suffix'  => 'wyvern_leather',
            'element' => MaterialElement::PHYSICAL,
        ],
        // Tier 4 [quality 1.9+]
        'manticore_leather'      => [
            'name'    => 'Manticore Leather',
            'icon'    => '/icon/leathers/leather_4.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 23,
            'quality' => 1.8,
            'prefix'  => '',
            'suffix'  => 'manticore_leather',
            'element' => MaterialElement::FIRE,
        ],
        'chimera_leather'        => [
            'name'    => 'Chimera Leather',
            'icon'    => '/icon/leathers/leather_13.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 23,
            'quality' => 1.8,
            'prefix'  => '',
            'suffix'  => 'chimera_leather',
            'element' => MaterialElement::WATER,
        ],
        'harpy_leather'          => [
            'name'    => 'Harpy Leather',
            'icon'    => '/icon/leathers/leather_11.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 23,
            'quality' => 1.8,
            'prefix'  => '',
            'suffix'  => 'harpy_leather',
            'element' => MaterialElement::AIR,
        ],
        'cave_snake_leather'     => [
            'name'    => 'Cave Snake Leather',
            'icon'    => '/icon/leathers/leather_18.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 23,
            'quality' => 1.8,
            'prefix'  => '',
            'suffix'  => 'cave_snake_leather',
            'element' => MaterialElement::EARTH,
        ],
        'unicorn_leather'        => [
            'name'    => 'Unicorn Leather',
            'icon'    => '/icon/leathers/leather_10.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 25,
            'quality' => 1.85,
            'prefix'  => '',
            'suffix'  => 'unicorn_leather',
            'element' => MaterialElement::LIFE,
        ],
        'night_beast_leather'    => [
            'name'    => 'Night Beast Leather',
            'icon'    => '/icon/leathers/leather_22.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 25,
            'quality' => 1.85,
            'prefix'  => '',
            'suffix'  => 'night_beast_leather',
            'element' => MaterialElement::DEATH,
        ],
        'elephant_leather'       => [
            'name'    => 'Elephant Leather',
            'icon'    => '/icon/leathers/leather_17.png',
            'type'    => MaterialTypeInterface::LEATHER,
            'level'   => 27,
            'quality' => 1.9,
            'prefix'  => '',
            'suffix'  => 'elephant_leather',
            'element' => MaterialElement::PHYSICAL,
        ],
    ];
}
