<?php

declare(strict_types=1);

namespace Item\Material\DataProvider;

use Item\Material\Element\MaterialElement;
use Item\Type\Material\MaterialTypeInterface;

class Metal extends AbstractMaterialDataProvider
{
    protected static array $materials = [
        // Tier 1
        'copper'            => [
            'name'    => 'Copper',
            'icon'    => '/img/icon/metals/copper.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 1,
            'quality' => 0.8,
            'prefix'  => 'copper',
            'suffix'  => '',
            'element' => MaterialElement::PHYSICAL,
        ],
        'iron'              => [
            'name'    => 'Iron',
            'icon'    => '/img/icon/metals/iron.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 1,
            'quality' => 1.0,
            'prefix'  => 'iron',
            'suffix'  => '',
            'element' => MaterialElement::PHYSICAL,
        ],
        'silver'            => [
            'name'    => 'Silver',
            'icon'    => '/img/icon/metals/silver.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 3,
            'quality' => 1.1,
            'prefix'  => 'silver',
            'suffix'  => '',
            'element' => MaterialElement::LIFE,
        ],
        // Tier 2
        'gold'              => [
            'name'    => 'Gold',
            'icon'    => '/img/icon/metals/gold.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 4,
            'quality' => 1.2,
            'prefix'  => 'gold',
            'suffix'  => '',
            'element' => MaterialElement::FIRE,
        ],
        'agatyp'            => [
            'name'    => 'Agatyp',
            'icon'    => '/img/icon/metals/agatyp.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 6,
            'quality' => 1.25,
            'prefix'  => 'agatyp',
            'suffix'  => '',
            'element' => MaterialElement::WATER,
        ],
        'white_metal'       => [
            'name'    => 'White Metal',
            'icon'    => '/img/icon/metals/talc.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 8,
            'quality' => 1.3,
            'prefix'  => 'white_metal',
            'suffix'  => '',
            'element' => MaterialElement::AIR,
        ],
        'miteril'           => [
            'name'    => 'Miteril',
            'icon'    => '/img/icon/metals/miteril.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 10,
            'quality' => 1.35,
            'prefix'  => 'miteril',
            'suffix'  => '',
            'element' => MaterialElement::EARTH,
        ],
        'doom_metal'        => [
            'name'    => 'Doom Metal',
            'icon'    => '/img/icon/metals/doom.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 12,
            'quality' => 1.4,
            'prefix'  => 'doom_metal',
            'suffix'  => '',
            'element' => MaterialElement::DEATH,
        ],
        // Tier 3
        'crystalline_metal' => [
            'name'    => 'Crystalline Metal',
            'icon'    => '/img/icon/metals/crystal.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 14,
            'quality' => 1.5,
            'prefix'  => 'crystalline_metal',
            'suffix'  => '',
            'element' => MaterialElement::PHYSICAL,
        ],
        'meteorite'         => [
            'name'    => 'Meteorite',
            'icon'    => '/img/icon/metals/meteorite.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 15,
            'quality' => 1.55,
            'prefix'  => 'meteorite',
            'suffix'  => '',
            'element' => MaterialElement::FIRE,
        ],
        'mithril'           => [
            'name'    => 'Mithril',
            'icon'    => '/img/icon/metals/mithril.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 16,
            'quality' => 1.6,
            'prefix'  => 'mithril',
            'suffix'  => '',
            'element' => MaterialElement::WATER,
        ],
        'valorite'          => [
            'name'    => 'Valorite',
            'icon'    => '/img/icon/metals/valorite.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 17,
            'quality' => 1.65,
            'prefix'  => 'valorite',
            'suffix'  => '',
            'element' => MaterialElement::AIR,
        ],
        'verite'            => [
            'name'    => 'Verite',
            'icon'    => '/img/icon/metals/verite.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 18,
            'quality' => 1.7,
            'prefix'  => 'verite',
            'suffix'  => '',
            'element' => MaterialElement::EARTH,
        ],
        'black_metal'       => [
            'name'    => 'Black Metal',
            'icon'    => '/img/icon/metals/black.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 20,
            'quality' => 1.75,
            'prefix'  => 'black_metal',
            'suffix'  => '',
            'element' => MaterialElement::DEATH,
        ],
        'heavenly_metal'    => [
            'name'    => 'Heavenly Metal',
            'icon'    => '/img/icon/metals/heaven.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 21,
            'quality' => 1.75,
            'prefix'  => 'heavenly_metal',
            'suffix'  => '',
            'element' => MaterialElement::LIFE,
        ],
        // Tier 4
        'titan'             => [
            'name'    => 'Titan',
            'icon'    => '/img/icon/metals/titan.png',
            'type'    => MaterialTypeInterface::METAL,
            'level'   => 23,
            'quality' => 1.9,
            'prefix'  => 'titan',
            'suffix'  => '',
            'element' => MaterialElement::PHYSICAL,
        ],
    ];
}
