<?php

declare(strict_types=1);

namespace Tests\Item\Affix\Type;

use Item\Affix\Type\AffixType;
use Item\ItemException;
use PHPUnit\Framework\TestCase;

class AffixTypeTest extends TestCase
{
    /**
     * @dataProvider successDataProvider
     * @param int $id
     * @param string $exceptedName
     * @throws ItemException
     */
    public function testAffixTypeCreateSuccess(int $id, string $exceptedName): void
    {
        $type = new AffixType($id);

        self::assertEquals($id, $type->getId());
        self::assertEquals($exceptedName, $type->getName());
    }

    public function testAffixTypeCreateFail(): void
    {
        $id = 500;
        $this->expectException(ItemException::class);
        $this->expectExceptionMessage(ItemException::UNKNOWN_AFFIX_TYPE . ': ' . $id);
        new AffixType($id);
    }

    /**
     * @return array
     */
    public function successDataProvider(): array
    {
        return [
            // base
            [
                1,
                'addLife',
            ],
            [
                2,
                'addMana',
            ],
            [
                3,
                'increaseLife',
            ],
            [
                4,
                'increaseMana',
            ],
            [
                5,
                'addLifeRegen',
            ],
            [
                6,
                'addManaRegen',
            ],
            [
                7,
                'addStamina',
            ],
            [
                8,
                'addMaxHorror',
            ],
            [
                9,
                'addStrength',
            ],
            [
                10,
                'addDexterity',
            ],
            [
                11,
                'addIntelligence',
            ],
            [
                12,
                'addWill',
            ],
            [
                13,
                'addEndurance',
            ],
            [
                14,
                'addPercipience',
            ],
            [
                15,
                'addCharisma',
            ],
            [
                16,
                'addLuck',
            ],
            [
                17,
                'addBeltSlot',
            ],
            [
                18,
                'addStaminaCost',
            ],
            [
                19,
                'bonusConcentration',
            ],
            [
                20,
                'bonusCunning',
            ],
            [
                21,
                'bonusRage',
            ],
            [
                22,
                'increaseGold',
            ],
            [
                23,
                'Might',
            ],
            [
                24,
                'Magic',
            ],
            [
                25,
                'Brutality',
            ],
            [
                26,
                'Fragility',
            ],
            [
                27,
                'Brute Force',
            ],
            [
                28,
                'Fragile Mind',
            ],

            // offense
            [
                100,
                'addPhysicalDamage',
            ],
            [
                101,
                'addFireDamage',
            ],
            [
                102,
                'addWaterDamage',
            ],
            [
                103,
                'addAirDamage',
            ],
            [
                104,
                'addEarthDamage',
            ],
            [
                105,
                'addLifeDamage',
            ],
            [
                106,
                'addDeathDamage',
            ],
            [
                107,
                'increasePhysicalDamage',
            ],
            [
                108,
                'increaseFireDamage',
            ],
            [
                109,
                'increaseWaterDamage',
            ],
            [
                110,
                'increaseAirDamage',
            ],
            [
                111,
                'increaseEarthDamage',
            ],
            [
                112,
                'increaseLifeDamage',
            ],
            [
                113,
                'increaseDeathDamage',
            ],
            [
                114,
                'addAccuracy',
            ],
            [
                115,
                'addMagicAccuracy',
            ],
            [
                116,
                'increaseAccuracy',
            ],
            [
                117,
                'increaseMagicAccuracy',
            ],
            [
                118,
                'increaseAttackSpeed',
            ],
            [
                119,
                'increaseCastSpeed',
            ],
            [
                120,
                'increaseCriticalChance',
            ],
            [
                121,
                'addCriticalMultiplier',
            ],
            [
                122,
                'addBlockIgnore',
            ],
            [
                123,
                'addVampirism',
            ],
            [
                124,
                'addMagicVampirism',
            ],
            [
                125,
                'addDamageMultiplier',
            ],
            [
                126,
                'doublePhysicalDamage',
            ],
            [
                127,
                'doubleFireDamage',
            ],
            [
                128,
                'doubleWaterDamage',
            ],
            [
                129,
                'doubleAirDamage',
            ],
            [
                130,
                'doubleEarthDamage',
            ],
            [
                131,
                'doubleLifeDamage',
            ],
            [
                132,
                'doubleDeathDamage',
            ],
            [
                133,
                'Mobility',
            ],
            [
                134,
                'Magic Mobility',
            ],
            [
                135,
                'Enchant',
            ],

            // defense
            [
                200,
                'addPhysicalResist',
            ],
            [
                201,
                'addFireResist',
            ],
            [
                202,
                'addWaterResist',
            ],
            [
                203,
                'addAirResist',
            ],
            [
                204,
                'addEarthResist',
            ],
            [
                205,
                'addLifeResist',
            ],
            [
                206,
                'addDeathResist',
            ],
            [
                207,
                'addMaxPhysicalResists',
            ],
            [
                208,
                'addMaxFireResist',
            ],
            [
                209,
                'addMaxWaterResist',
            ],
            [
                210,
                'addMaxAirResist',
            ],
            [
                211,
                'addMaxEarthResist',
            ],
            [
                212,
                'addMaxLifeResist',
            ],
            [
                213,
                'addMaxDeathResist',
            ],
            [
                214,
                'addMaxAllResist',
            ],
            [
                215,
                'addDefense',
            ],
            [
                216,
                'addMagicDefense',
            ],
            [
                217,
                'increaseDefense',
            ],
            [
                218,
                'increaseMagicDefense',
            ],
            [
                219,
                'addBlock',
            ],
            [
                220,
                'addMagicBlock',
            ],
            [
                221,
                'addMentalBarrier',
            ],
            [
                222,
                'addGlobalResist',
            ],
            [
                223,
                'addDodge',
            ],
            [
                224,
                'addHidden',
            ],
        ];
    }
}
