<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Axe extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // one hand
        1251 => [
            'id'               => 1251,
            'name'             => 'Lumberjack‘s Axe',
            'icon'             => '/img/icon/items/axes/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 1,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1252 => [
            'id'               => 1252,
            'name'             => 'Battle Axe',
            'icon'             => '/img/icon/items/axes/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 5,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1253 => [
            'id'               => 1253,
            'name'             => 'Northern Axe',
            'icon'             => '/img/icon/items/axes/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 9,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1254 => [
            'id'               => 1254,
            'name'             => 'Dwarven Axe',
            'icon'             => '/img/icon/items/axes/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 13,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1255 => [
            'id'               => 1255,
            'name'             => 'Tomahawk',
            'icon'             => '/img/icon/items/axes/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 18,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1256 => [
            'id'               => 1256,
            'name'             => 'Berserker Axe',
            'icon'             => '/img/icon/items/axes/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 150,
            'min_level'        => 22,
            'strength'         => 0.9,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        // two hand
        1257 => [
            'id'               => 1257,
            'name'             => 'Two-handed Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1258 => [
            'id'               => 1258,
            'name'             => 'Cleaver Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1259 => [
            'id'               => 1259,
            'name'             => 'Broad Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1260 => [
            'id'               => 1260,
            'name'             => 'Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 180,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1261 => [
            'id'               => 1261,
            'name'             => 'Executioner‘s Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1262 => [
            'id'               => 1262,
            'name'             => 'Gothic Axe',
            'icon'             => '/img/icon/items/axes/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        // one hand heavy
        1263 => [
            'id'               => 1263,
            'name'             => 'Heavy Axe',
            'icon'             => '/img/icon/items/axes/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1264 => [
            'id'               => 1264,
            'name'             => 'Jagged Axe',
            'icon'             => '/img/icon/items/axes/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1265 => [
            'id'               => 1265,
            'name'             => 'Heavy Battle Axe',
            'icon'             => '/img/icon/items/axes/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1266 => [
            'id'               => 1266,
            'name'             => 'Chopper',
            'icon'             => '/img/icon/items/axes/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::AVERAGE,
            'weight'           => 190,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1267 => [
            'id'               => 1267,
            'name'             => 'Deadman‘s Glory',
            'icon'             => '/img/icon/items/axes/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1268 => [
            'id'               => 1268,
            'name'             => 'Shieldbreaker',
            'icon'             => '/img/icon/items/axes/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 70,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        // two hand heavy
        1269 => [
            'id'               => 1269,
            'name'             => 'Heavy Cleaver',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 1,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1270 => [
            'id'               => 1270,
            'name'             => 'Ogre Axe',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 5,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1271 => [
            'id'               => 1271,
            'name'             => 'Heavy War Axe',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 9,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1272 => [
            'id'               => 1272,
            'name'             => 'Skull Splitter',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 13,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1273 => [
            'id'               => 1273,
            'name'             => 'Cannibal‘s Axe',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 18,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1274 => [
            'id'               => 1274,
            'name'             => 'Widowmaker',
            'icon'             => '/img/icon/items/axes/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_AXE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 22,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.damageMultiplier',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
