<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Armor\ArmorTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;

class Boots extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // robe
        5301 => [
            'id'               => 5301,
            'name'             => 'Wanderer‘s Shoes',
            'icon'             => '/img/icon/items/boots/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 15,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5302 => [
            'id'               => 5302,
            'name'             => 'Adept Shoes',
            'icon'             => '/img/icon/items/boots/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 15,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5303 => [
            'id'               => 5303,
            'name'             => 'Priest‘s Shoes',
            'icon'             => '/img/icon/items/boots/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 15,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5304 => [
            'id'               => 5304,
            'name'             => 'Magician‘s Shoes',
            'icon'             => '/img/icon/items/boots/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 15,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5305 => [
            'id'               => 5305,
            'name'             => 'Elven Shoes',
            'icon'             => '/img/icon/items/boots/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5306 => [
            'id'               => 5306,
            'name'             => 'Boots of Wisdom',
            'icon'             => '/img/icon/items/boots/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        // light
        5311 => [
            'id'               => 5311,
            'name'             => 'Footcloths',
            'icon'             => '/img/icon/items/boots/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5312 => [
            'id'               => 5312,
            'name'             => 'Boots',
            'icon'             => '/img/icon/items/boots/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5313 => [
            'id'               => 5313,
            'name'             => 'Thief‘s Boots',
            'icon'             => '/img/icon/items/boots/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5314 => [
            'id'               => 5314,
            'name'             => 'Quilted Boots',
            'icon'             => '/img/icon/items/boots/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5315 => [
            'id'               => 5315,
            'name'             => 'Cursed Boots',
            'icon'             => '/img/icon/items/boots/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5316 => [
            'id'               => 5316,
            'name'             => 'Boots of Oath',
            'icon'             => '/img/icon/items/boots/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // middle
        5321 => [
            'id'               => 5321,
            'name'             => 'Chainmail Boots',
            'icon'             => '/img/icon/items/boots/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 1,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5322 => [
            'id'               => 5322,
            'name'             => 'Militiaman‘s Boots',
            'icon'             => '/img/icon/items/boots/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 5,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5323 => [
            'id'               => 5323,
            'name'             => 'Riveted Chainmail Boots',
            'icon'             => '/img/icon/items/boots/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 9,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5324 => [
            'id'               => 5324,
            'name'             => 'Forged Boots',
            'icon'             => '/img/icon/items/boots/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 13,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5325 => [
            'id'               => 5325,
            'name'             => 'Dwarven Boots',
            'icon'             => '/img/icon/items/boots/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 18,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5326 => [
            'id'               => 5326,
            'name'             => 'Light Plate Boots',
            'icon'             => '/img/icon/items/boots/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 22,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // heavy
        5331 => [
            'id'               => 5331,
            'name'             => 'Miner‘s Boots',
            'icon'             => '/img/icon/items/boots/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5332 => [
            'id'               => 5332,
            'name'             => 'Blacksmith‘s Boots',
            'icon'             => '/img/icon/items/boots/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5333 => [
            'id'               => 5333,
            'name'             => 'Guard Boots',
            'icon'             => '/img/icon/items/boots/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5334 => [
            'id'               => 5334,
            'name'             => 'Orc Boots',
            'icon'             => '/img/icon/items/boots/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5335 => [
            'id'               => 5335,
            'name'             => 'Knight‘s Boots',
            'icon'             => '/img/icon/items/boots/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5336 => [
            'id'               => 5336,
            'name'             => 'Plate Boots',
            'icon'             => '/img/icon/items/boots/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::BOOTS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::BOOTS,
            'section_type_id'  => SectionTypeInterface::BOOTS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
    ];
}
