<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Bow extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        1051 => [
            'id'               => 1051,
            'name'             => 'Longbow',
            'icon'             => '/img/icon/items/bows/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'suffix'  => '%',
                    'prefix'  => '',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1052 => [
            'id'               => 1052,
            'name'             => 'Short Bow',
            'icon'             => '/img/icon/items/bows/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 1,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1053 => [
            'id'               => 1053,
            'name'             => 'Composite Bow',
            'icon'             => '/img/icon/items/bows/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1054 => [
            'id'               => 1054,
            'name'             => 'Hunting Bow',
            'icon'             => '/img/icon/items/bows/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 5,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1055 => [
            'id'               => 1055,
            'name'             => 'War Longbow',
            'icon'             => '/img/icon/items/bows/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1056 => [
            'id'               => 1056,
            'name'             => 'Carved Bow',
            'icon'             => '/img/icon/items/bows/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 9,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1057 => [
            'id'               => 1057,
            'name'             => 'Elven Bow',
            'icon'             => '/img/icon/items/bows/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1058 => [
            'id'               => 1058,
            'name'             => 'Compound Bow',
            'icon'             => '/img/icon/items/bows/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 13,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1059 => [
            'id'               => 1059,
            'name'             => 'Amazon Bow',
            'icon'             => '/img/icon/items/bows/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1060 => [
            'id'               => 1060,
            'name'             => 'Soul Piercer',
            'icon'             => '/img/icon/items/bows/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 18,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1061 => [
            'id'               => 1061,
            'name'             => 'Royal Bow',
            'icon'             => '/img/icon/items/bows/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 120,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
        1062 => [
            'id'               => 1062,
            'name'             => 'Bow of the Night',
            'icon'             => '/img/icon/items/bows/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::BOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 90,
            'min_level'        => 22,
            'strength'         => 0.5,
            'intelligence'     => 0.0,
            'dexterity'        => 0.8,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.increaseAccuracy',
                    'value'   => 25,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
