<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Crossbow extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        1001 => [
            'id'               => 1001,
            'name'             => 'Light Crossbow',
            'icon'             => '/img/icon/items/crossbow/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 1,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1002 => [
            'id'               => 1002,
            'name'             => 'Militiaman‘s Crossbow',
            'icon'             => '/img/icon/items/crossbow/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 1,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1003 => [
            'id'               => 1003,
            'name'             => 'Heavy crossbow',
            'icon'             => '/img/icon/items/crossbow/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1004 => [
            'id'               => 1004,
            'name'             => 'Arquebus',
            'icon'             => '/img/icon/items/crossbow/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 5,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1005 => [
            'id'               => 1005,
            'name'             => 'Crossbow',
            'icon'             => '/img/icon/items/crossbow/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 5,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1006 => [
            'id'               => 1006,
            'name'             => 'Double crossbow',
            'icon'             => '/img/icon/items/crossbow/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1007 => [
            'id'               => 1007,
            'name'             => 'Self-loading crossbow',
            'icon'             => '/img/icon/items/crossbow/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 9,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1008 => [
            'id'               => 1008,
            'name'             => 'Siege Crossbow',
            'icon'             => '/img/icon/items/crossbow/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 9,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1009 => [
            'id'               => 1009,
            'name'             => 'Double Heavy Crossbow',
            'icon'             => '/img/icon/items/crossbow/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1010 => [
            'id'               => 1010,
            'name'             => 'Rapid Fire Crossbow',
            'icon'             => '/img/icon/items/crossbow/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 13,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1011 => [
            'id'               => 1011,
            'name'             => 'Dwarven Crossbow',
            'icon'             => '/img/icon/items/crossbow/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 13,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1012 => [
            'id'               => 1012,
            'name'             => 'Scourge of Magicians',
            'icon'             => '/img/icon/items/crossbow/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1013 => [
            'id'               => 1013,
            'name'             => 'Compound crossbow',
            'icon'             => '/img/icon/items/crossbow/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 18,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1014 => [
            'id'               => 1014,
            'name'             => 'The Storm of Knights',
            'icon'             => '/img/icon/items/crossbow/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 210,
            'min_level'        => 18,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1015 => [
            'id'               => 1015,
            'name'             => 'Ballista',
            'icon'             => '/img/icon/items/crossbow/10.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 250,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1016 => [
            'id'               => 1016,
            'name'             => 'Multi-shot crossbow',
            'icon'             => '/img/icon/items/crossbow/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 160,
            'min_level'        => 22,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1018 => [
            'id'               => 1018,
            'name'             => 'Hydra Crossbow',
            'icon'             => '/img/icon/items/crossbow/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 22,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1019 => [
            'id'               => 1019,
            'name'             => 'Dragon Slayer',
            'icon'             => '/img/icon/items/crossbow/10.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::CROSSBOW,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'armor_type_id'    => null,
            'potion_type_id'   => null,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 60,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 300,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
