<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Armor\ArmorTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;

class Gloves extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // robe
        5201 => [
            'id'               => 5201,
            'name'             => 'Wanderer‘s Gloves',
            'icon'             => '/img/icon/items/gloves/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5202 => [
            'id'               => 5202,
            'name'             => 'Adept Gloves',
            'icon'             => '/img/icon/items/gloves/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5203 => [
            'id'               => 5203,
            'name'             => 'Priest‘s Gloves',
            'icon'             => '/img/icon/items/gloves/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5204 => [
            'id'               => 5204,
            'name'             => 'Magician‘s Gloves',
            'icon'             => '/img/icon/items/gloves/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5205 => [
            'id'               => 5205,
            'name'             => 'Elven Gloves',
            'icon'             => '/img/icon/items/gloves/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5206 => [
            'id'               => 5206,
            'name'             => 'Gloves of Wisdom',
            'icon'             => '/img/icon/items/gloves/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 15,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        // light
        5211 => [
            'id'               => 5211,
            'name'             => 'Gloves',
            'icon'             => '/img/icon/items/gloves/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5212 => [
            'id'               => 5212,
            'name'             => 'Mittens',
            'icon'             => '/img/icon/items/gloves/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5213 => [
            'id'               => 5213,
            'name'             => 'Thief‘s Gloves',
            'icon'             => '/img/icon/items/gloves/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5214 => [
            'id'               => 5214,
            'name'             => 'Quilted Gloves',
            'icon'             => '/img/icon/items/gloves/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5215 => [
            'id'               => 5215,
            'name'             => 'Cursed Gloves',
            'icon'             => '/img/icon/items/gloves/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5216 => [
            'id'               => 5216,
            'name'             => 'Gloves of Oath',
            'icon'             => '/img/icon/items/gloves/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 25,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // middle
        5221 => [
            'id'               => 5221,
            'name'             => 'Chainmail Gloves',
            'icon'             => '/img/icon/items/gloves/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 1,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5222 => [
            'id'               => 5222,
            'name'             => 'Militia Gloves',
            'icon'             => '/img/icon/items/gloves/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 5,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5223 => [
            'id'               => 5223,
            'name'             => 'Riveted Chainmail Gloves',
            'icon'             => '/img/icon/items/gloves/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 9,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5224 => [
            'id'               => 5224,
            'name'             => 'Forged Gloves',
            'icon'             => '/img/icon/items/gloves/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 13,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5225 => [
            'id'               => 5225,
            'name'             => 'Dwarven Gloves',
            'icon'             => '/img/icon/items/gloves/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 18,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5226 => [
            'id'               => 5226,
            'name'             => 'Light Plate Gloves',
            'icon'             => '/img/icon/items/gloves/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 40,
            'min_level'        => 22,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // heavy
        5231 => [
            'id'               => 5231,
            'name'             => 'Miner‘s Gloves',
            'icon'             => '/img/icon/items/gloves/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5232 => [
            'id'               => 5232,
            'name'             => 'Blacksmith‘s Gloves',
            'icon'             => '/img/icon/items/gloves/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5233 => [
            'id'               => 5233,
            'name'             => 'Guardian Gloves',
            'icon'             => '/img/icon/items/gloves/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5234 => [
            'id'               => 5234,
            'name'             => 'Orc Gloves',
            'icon'             => '/img/icon/items/gloves/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5235 => [
            'id'               => 5235,
            'name'             => 'Knight‘s Gloves',
            'icon'             => '/img/icon/items/gloves/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5236 => [
            'id'               => 5236,
            'name'             => 'Plate Gloves',
            'icon'             => '/img/icon/items/gloves/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::GLOVES,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::GLOVES,
            'section_type_id'  => SectionTypeInterface::GLOVES,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 60,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
    ];
}
