<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Armor\ArmorTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;

class Legs extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // robe
        5401 => [
            'id'               => 5401,
            'name'             => 'Wanderer Belt',
            'icon'             => '/img/icon/items/legs/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 20,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5402 => [
            'id'               => 5402,
            'name'             => 'Adept Belt',
            'icon'             => '/img/icon/items/legs/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 20,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5403 => [
            'id'               => 5403,
            'name'             => 'Priest‘s Belt',
            'icon'             => '/img/icon/items/legs/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 20,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5404 => [
            'id'               => 5404,
            'name'             => 'Magician‘s Belt',
            'icon'             => '/img/icon/items/legs/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 20,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5405 => [
            'id'               => 5405,
            'name'             => 'Elven Pants',
            'icon'             => '/img/icon/items/legs/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5406 => [
            'id'               => 5406,
            'name'             => 'Pants of Wisdom',
            'icon'             => '/img/icon/items/legs/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 3,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        // light
        5411 => [
            'id'               => 5411,
            'name'             => 'Trousers',
            'icon'             => '/img/icon/items/legs/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5412 => [
            'id'               => 5412,
            'name'             => 'Legguards',
            'icon'             => '/img/icon/items/legs/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5413 => [
            'id'               => 5413,
            'name'             => 'Thief‘s Pants',
            'icon'             => '/img/icon/items/legs/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5414 => [
            'id'               => 5414,
            'name'             => 'Quilted Pants',
            'icon'             => '/img/icon/items/legs/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5415 => [
            'id'               => 5415,
            'name'             => 'Cursed Pants',
            'icon'             => '/img/icon/items/legs/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5416 => [
            'id'               => 5416,
            'name'             => 'Oath Pants',
            'icon'             => '/img/icon/items/legs/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 3,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        // middle
        5421 => [
            'id'               => 5421,
            'name'             => 'Chainmail Pants',
            'icon'             => '/img/icon/items/legs/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 1,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5422 => [
            'id'               => 5422,
            'name'             => 'Militiaman‘s Pants',
            'icon'             => '/img/icon/items/legs/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 5,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5423 => [
            'id'               => 5423,
            'name'             => 'Riveted Chainmail Pants',
            'icon'             => '/img/icon/items/legs/10.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 9,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5424 => [
            'id'               => 5424,
            'name'             => 'Forged Leggings',
            'icon'             => '/img/icon/items/legs/10.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 13,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5425 => [
            'id'               => 5425,
            'name'             => 'Dwarven Leggings',
            'icon'             => '/img/icon/items/legs/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 18,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5426 => [
            'id'               => 5426,
            'name'             => 'Light Plate Greaves',
            'icon'             => '/img/icon/items/legs/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 22,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 3,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        // heavy
        5431 => [
            'id'               => 5431,
            'name'             => 'Miner‘s Leggings',
            'icon'             => '/img/icon/items/legs/11.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5432 => [
            'id'               => 5432,
            'name'             => 'Blacksmith‘s Leggings',
            'icon'             => '/img/icon/items/legs/11.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5433 => [
            'id'               => 5433,
            'name'             => 'Guard‘s Leggings',
            'icon'             => '/img/icon/items/legs/11.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5434 => [
            'id'               => 5434,
            'name'             => 'Orc Leggings',
            'icon'             => '/img/icon/items/legs/12.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5435 => [
            'id'               => 5435,
            'name'             => 'Knight‘s Leggings',
            'icon'             => '/img/icon/items/legs/12.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 2,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
        5436 => [
            'id'               => 5436,
            'name'             => 'Plate Leggings',
            'icon'             => '/img/icon/items/legs/12.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::LEGS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::LEGS,
            'section_type_id'  => SectionTypeInterface::LEGS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [
                [
                    'name'    => 'base.beltSlot',
                    'value'   => 3,
                    'quality' => false,
                    'prefix'  => '+',
                    'suffix'  => '',
                ],
            ],
        ],
    ];
}
