<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Mace extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // one hand
        1301 => [
            'id'               => 1301,
            'name'             => 'Club',
            'icon'             => '/img/icon/items/maces/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 180,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1302 => [
            'id'               => 1302,
            'name'             => 'Mace',
            'icon'             => '/img/icon/items/maces/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 180,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1303 => [
            'id'               => 1303,
            'name'             => 'Spiked Mace',
            'icon'             => '/img/icon/items/maces/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 180,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1304 => [
            'id'               => 1304,
            'name'             => 'Flail',
            'icon'             => '/img/icon/items/maces/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1305 => [
            'id'               => 1305,
            'name'             => 'Buzdygan',
            'icon'             => '/img/icon/items/maces/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1306 => [
            'id'               => 1306,
            'name'             => 'Angelic Wrath',
            'icon'             => '/img/icon/items/maces/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 180,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 90,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        // two hand
        1307 => [
            'id'               => 1307,
            'name'             => 'Two-handed Cudgel',
            'icon'             => '/img/icon/items/maces/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 210,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1308 => [
            'id'               => 1308,
            'name'             => 'Two-handed Hammer',
            'icon'             => '/img/icon/items/maces/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1309 => [
            'id'               => 1309,
            'name'             => 'Pood Hammer',
            'icon'             => '/img/icon/items/maces/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1310 => [
            'id'               => 1310,
            'name'             => 'Two-handed Flail',
            'icon'             => '/img/icon/items/maces/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1311 => [
            'id'               => 1311,
            'name'             => 'Hammer of Dwarves',
            'icon'             => '/img/icon/items/maces/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        1312 => [
            'id'               => 1312,
            'name'             => 'Messenger of Death',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 210,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 80,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
            ],
        ],
        // one hand heavy
        1313 => [
            'id'               => 1313,
            'name'             => 'Hammer',
            'icon'             => '/img/icon/items/maces/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 200,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1314 => [
            'id'               => 1314,
            'name'             => 'Blacksmith‘s Hammer',
            'icon'             => '/img/icon/items/maces/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 200,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1315 => [
            'id'               => 1315,
            'name'             => 'War Hammer',
            'icon'             => '/img/icon/items/maces/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 200,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1316 => [
            'id'               => 1316,
            'name'             => 'Heavy Spiked Mace',
            'icon'             => '/img/icon/items/maces/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 200,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1317 => [
            'id'               => 1317,
            'name'             => 'Morning Star',
            'icon'             => '/img/icon/items/maces/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 200,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1318 => [
            'id'               => 1318,
            'name'             => 'Shepherd‘s Wrath',
            'icon'             => '/img/icon/items/maces/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 200,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        // two hand heavy
        1319 => [
            'id'               => 1319,
            'name'             => 'Heavy Two-Handed Hammer',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 1,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1320 => [
            'id'               => 1320,
            'name'             => 'Sledgehammer',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 250,
            'min_level'        => 5,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1321 => [
            'id'               => 1321,
            'name'             => 'Bonebreaker',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 9,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1322 => [
            'id'               => 1322,
            'name'             => 'Hammer of Giants',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 13,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1323 => [
            'id'               => 1323,
            'name'             => 'Hammer of Death',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 18,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1324 => [
            'id'               => 1324,
            'name'             => 'King‘s Hammer',
            'icon'             => '/img/icon/items/maces/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_MACE,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 250,
            'min_level'        => 22,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 55,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalStun',
                    'value'   => 1,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
