<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Armor\ArmorTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;

class Shoulders extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // robe
        5501 => [
            'id'               => 5501,
            'name'             => 'Wanderer‘s Armlets',
            'icon'             => '/img/icon/items/shoulders/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5502 => [
            'id'               => 5502,
            'name'             => 'Adept‘s Armbands',
            'icon'             => '/img/icon/items/shoulders/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5503 => [
            'id'               => 5503,
            'name'             => 'Priest‘s Armbands',
            'icon'             => '/img/icon/items/shoulders/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5504 => [
            'id'               => 5504,
            'name'             => 'Magician‘s Armbands',
            'icon'             => '/img/icon/items/shoulders/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5505 => [
            'id'               => 5505,
            'name'             => 'Elven Armbands',
            'icon'             => '/img/icon/items/shoulders/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        5506 => [
            'id'               => 5506,
            'name'             => 'Armbands of Wisdom',
            'icon'             => '/img/icon/items/shoulders/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::ROBE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::CLOTH,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 20,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
            ],
            'stats'            => [],
        ],
        // light
        5511 => [
            'id'               => 5511,
            'name'             => 'Armbands',
            'icon'             => '/img/icon/items/shoulders/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5512 => [
            'id'               => 5512,
            'name'             => 'Shoulders',
            'icon'             => '/img/icon/items/shoulders/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5513 => [
            'id'               => 5513,
            'name'             => 'Thief‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5514 => [
            'id'               => 5514,
            'name'             => 'Quilted Shoulders',
            'icon'             => '/img/icon/items/shoulders/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5515 => [
            'id'               => 5515,
            'name'             => 'Cursed Shoulders',
            'icon'             => '/img/icon/items/shoulders/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5516 => [
            'id'               => 5516,
            'name'             => 'Shoulders of Oath',
            'icon'             => '/img/icon/items/shoulders/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::LIGHT,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::LEATHER,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 35,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 0.0,
            'dexterity'        => 1.0,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // middle
        5521 => [
            'id'               => 5521,
            'name'             => 'Chainmail Armlets',
            'icon'             => '/img/icon/items/shoulders/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 1,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5522 => [
            'id'               => 5522,
            'name'             => 'Militiaman‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 5,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5523 => [
            'id'               => 5523,
            'name'             => 'Riveted Chainmail Shoulders',
            'icon'             => '/img/icon/items/shoulders/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 9,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5524 => [
            'id'               => 5524,
            'name'             => 'Forged Shoulders',
            'icon'             => '/img/icon/items/shoulders/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 13,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5525 => [
            'id'               => 5525,
            'name'             => 'Dwarven Shoulders',
            'icon'             => '/img/icon/items/shoulders/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 18,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        5526 => [
            'id'               => 5526,
            'name'             => 'Light Plate Shoulders',
            'icon'             => '/img/icon/items/shoulders/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::MIDDLE,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 54,
            'min_level'        => 22,
            'strength'         => 0.6,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [],
            'stats'            => [],
        ],
        // heavy
        5531 => [
            'id'               => 5531,
            'name'             => 'Miner‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5532 => [
            'id'               => 5532,
            'name'             => 'Blacksmith‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5533 => [
            'id'               => 5533,
            'name'             => 'Guard‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5534 => [
            'id'               => 5534,
            'name'             => 'Orc Shoulders',
            'icon'             => '/img/icon/items/shoulders/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5535 => [
            'id'               => 5535,
            'name'             => 'Knight‘s Shoulders',
            'icon'             => '/img/icon/items/shoulders/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
        5536 => [
            'id'               => 5536,
            'name'             => 'Plate Shoulders',
            'icon'             => '/img/icon/items/shoulders/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::SHOULDERS,
            'armor_type_id'    => ArmorTypeInterface::HEAVY,
            'magic_type_id'    => MagicTypeInterface::SHOULDERS,
            'section_type_id'  => SectionTypeInterface::SHOULDERS,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MULTIPLE,
            'weight'           => 90,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::ADD_DEFENSE,
                AffixTypeInterface::INCREASE_DEFENSE,
                AffixTypeInterface::ADD_MAGIC_DEFENSE,
                AffixTypeInterface::INCREASE_MAGIC_DEFENSE,
            ],
            'stats'            => [],
        ],
    ];
}
