<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Staff extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        1101 => [
            'id'               => 1101,
            'name'             => 'Staff',
            'icon'             => '/img/icon/items/staffs/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1102 => [
            'id'               => 1102,
            'name'             => 'Carved Staff',
            'icon'             => '/img/icon/items/staffs/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1103 => [
            'id'               => 1103,
            'name'             => 'Ruby Staff',
            'icon'             => '/img/icon/items/staffs/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1104 => [
            'id'               => 1104,
            'name'             => 'War Staff',
            'icon'             => '/img/icon/items/staffs/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1105 => [
            'id'               => 1105,
            'name'             => 'Elven Staff',
            'icon'             => '/img/icon/items/staffs/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1106 => [
            'id'               => 1106,
            'name'             => 'Arbiter of Fates',
            'icon'             => '/img/icon/items/staffs/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::STAFF,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 105,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusConcentration',
                    'value'   => 50,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
