<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Sword extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        // one hand
        1201 => [
            'id'               => 1201,
            'name'             => 'Short Sword',
            'icon'             => '/img/icon/items/swords/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 130,
            'min_level'        => 1,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 6,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 6,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1202 => [
            'id'               => 1202,
            'name'             => 'Saber',
            'icon'             => '/img/icon/items/swords/05.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 130,
            'min_level'        => 5,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1203 => [
            'id'               => 1203,
            'name'             => 'Gladius',
            'icon'             => '/img/icon/items/swords/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 130,
            'min_level'        => 9,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1204 => [
            'id'               => 1204,
            'name'             => 'Sword of Wanderer',
            'icon'             => '/img/icon/items/swords/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 130,
            'min_level'        => 13,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1205 => [
            'id'               => 1205,
            'name'             => 'Katana',
            'icon'             => '/img/icon/items/swords/10.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 130,
            'min_level'        => 18,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1206 => [
            'id'               => 1206,
            'name'             => 'Knight‘s Sword',
            'icon'             => '/img/icon/items/swords/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 130,
            'min_level'        => 22,
            'strength'         => 0.8,
            'intelligence'     => 0.0,
            'dexterity'        => 0.6,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 110,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 9,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 9,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        // two hand
        1211 => [
            'id'               => 1211,
            'name'             => 'Two-handed Sword',
            'icon'             => '/img/icon/items/swords/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 12,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 12,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1212 => [
            'id'               => 1212,
            'name'             => 'Claymore',
            'icon'             => '/img/icon/items/swords/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1213 => [
            'id'               => 1213,
            'name'             => 'Flamberg',
            'icon'             => '/img/icon/items/swords/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1214 => [
            'id'               => 1214,
            'name'             => 'Espadon',
            'icon'             => '/img/icon/items/swords/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1215 => [
            'id'               => 1215,
            'name'             => 'Zweihander',
            'icon'             => '/img/icon/items/swords/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1216 => [
            'id'               => 1216,
            'name'             => 'Caliburs',
            'icon'             => '/img/icon/items/swords/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 170,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.5,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 18,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 18,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        // one hand heavy
        1221 => [
            'id'               => 1221,
            'name'             => 'Heavy Sword',
            'icon'             => '/img/icon/items/swords/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 1,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 6,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 6,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1222 => [
            'id'               => 1222,
            'name'             => 'Jagged Sword',
            'icon'             => '/img/icon/items/swords/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 5,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1223 => [
            'id'               => 1223,
            'name'             => 'Sword of Renegade',
            'icon'             => '/img/icon/items/swords/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 9,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 7,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1224 => [
            'id'               => 1224,
            'name'             => 'Scimitar',
            'icon'             => '/img/icon/items/swords/04.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 13,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1225 => [
            'id'               => 1225,
            'name'             => 'Shamshir',
            'icon'             => '/img/icon/items/swords/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 18,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 8,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1226 => [
            'id'               => 1226,
            'name'             => 'Bloodsucker',
            'icon'             => '/img/icon/items/swords/06.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 190,
            'min_level'        => 22,
            'strength'         => 1.0,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 75,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 9,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 9,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        // two hand heavy
        1231 => [
            'id'               => 1231,
            'name'             => 'Great Sword',
            'icon'             => '/img/icon/items/swords/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 1,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 12,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 12,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1232 => [
            'id'               => 1232,
            'name'             => 'Cleaver',
            'icon'             => '/img/icon/items/swords/07.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 5,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1233 => [
            'id'               => 1233,
            'name'             => 'Sword of Cutthroat',
            'icon'             => '/img/icon/items/swords/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 9,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 14,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1234 => [
            'id'               => 1234,
            'name'             => 'Blade of Giant',
            'icon'             => '/img/icon/items/swords/08.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 13,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1235 => [
            'id'               => 1235,
            'name'             => 'Armor Breaker',
            'icon'             => '/img/icon/items/swords/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 18,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 16,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1236 => [
            'id'               => 1236,
            'name'             => 'Sword of Darkness',
            'icon'             => '/img/icon/items/swords/09.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::TWO_HAND,
            'weapon_type_id'   => WeaponTypeInterface::TWO_HAND_HEAVY_SWORD,
            'magic_type_id'    => MagicTypeInterface::TWO_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::METAL,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 230,
            'min_level'        => 22,
            'strength'         => 1.1,
            'intelligence'     => 0.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_CAST_SPEED,
                AffixTypeInterface::INCREASE_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_MAGIC_ACCURACY,
                AffixTypeInterface::ADD_BLOCK_IGNORE,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.attackSpeed',
                    'value'   => 65,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 10,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 250,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.block',
                    'value'   => 18,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'defense.magicBlock',
                    'value'   => 18,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.blockIgnore',
                    'value'   => 100,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
