<?php

declare(strict_types=1);

namespace Item\Drawing\DataProvider;

use Item\Affix\Type\AffixTypeInterface;
use Item\Type\Equip\EquipTypeInterface;
use Item\Type\Gender\GenderTypeInterface;
use Item\Type\ItemTypeInterface;
use Item\Type\Magic\MagicTypeInterface;
use Item\Type\Material\MaterialTypeInterface;
use Item\Type\Section\SectionTypeInterface;
use Item\Type\Weapon\WeaponTypeInterface;

class Wand extends AbstractDrawingDataProvider
{
    protected static array $drawings = [
        1151 => [
            'id'               => 1151,
            'name'             => 'Disciple‘s Rod',
            'icon'             => '/img/icon/items/wands/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 15,
            'min_level'        => 1,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1152 => [
            'id'               => 1152,
            'name'             => 'Magic Wand',
            'icon'             => '/img/icon/items/wands/01.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::FEMALE,
            'weight'           => 15,
            'min_level'        => 5,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1153 => [
            'id'               => 1153,
            'name'             => 'Wand of Elements',
            'icon'             => '/img/icon/items/wands/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 15,
            'min_level'        => 9,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1154 => [
            'id'               => 1154,
            'name'             => 'Wizard‘s Wand',
            'icon'             => '/img/icon/items/wands/02.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 15,
            'min_level'        => 13,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1155 => [
            'id'               => 1155,
            'name'             => 'Phoenix Wand',
            'icon'             => '/img/icon/items/wands/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 15,
            'min_level'        => 18,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
        1156 => [
            'id'               => 1156,
            'name'             => 'Rod of Wisdom',
            'icon'             => '/img/icon/items/wands/03.png',
            'type_id'          => ItemTypeInterface::EQUIP,
            'equip_type_id'    => EquipTypeInterface::ONE_HAND,
            'weapon_type_id'   => WeaponTypeInterface::WAND,
            'magic_type_id'    => MagicTypeInterface::ONE_HAND_WEAPON,
            'section_type_id'  => SectionTypeInterface::RIGHT_HAND,
            'material_type_id' => MaterialTypeInterface::WOOD,
            'gender_type_id'   => GenderTypeInterface::MALE,
            'weight'           => 15,
            'min_level'        => 22,
            'strength'         => 0.0,
            'intelligence'     => 1.0,
            'dexterity'        => 0.0,
            'affix_exception'  => [
                AffixTypeInterface::INCREASE_ATTACK_SPEED,
                AffixTypeInterface::INCREASE_ACCURACY,
                AffixTypeInterface::ADD_ACCURACY,
            ],
            'stats'            => [
                [
                    'name'    => 'offense.castSpeed',
                    'value'   => 120,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '',
                ],
                [
                    'name'    => 'offense.criticalChance',
                    'value'   => 15,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'offense.criticalMultiplier',
                    'value'   => 200,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
                [
                    'name'    => 'base.bonusRage',
                    'value'   => 30,
                    'quality' => false,
                    'prefix'  => '',
                    'suffix'  => '%',
                ],
            ],
        ],
    ];
}
